version: "3"
services:
  mongodb:
    image: mongo
    container_name: mongodb
    ports:
      - 27017:27017
    environment:
      - MONGO_INITDB_ROOT_USERNAME=klaus
      - MONGO_INITDB_ROOT_PASSWORD=klaus123
    volumes:
      - mongo_data:/data/db
  backend:
    image: sai045/hrportalbackend:1.0.1
    container_name: hrportalbackend
    ports:
      - 5000:5000
    environment:
      - jwt_secret=secret
  frontend:
    image: sai045/hrportalfrontend:1.0.1
    container_name: hrportalfrontend
    ports:
      - 3000:3000
    environment:
      - REACT_APP_DOMIAN=http://localhost:5000/

volumes:
  mongo_data:
