version: '3'
services:
  backend:
    image: sai045/hrportalbackend:1.0.0
    container_name: hrportalbackend
    ports:
      - 5000:5000
    environment:
      - jwt_secret=secret
  mongodb:
    image: mongo:4.0.4
    container_name: mongo
    ports:
      - 27017:27017
    environment:
      - MONGO_INITDB_ROOT_USERNAME=klaus
      - MONGO_INITDB_ROOT_PASSWORD=klaus123
    volumes:
      - mongo_data:/data/db
  frontend:
    image: sai045/hrportalfrontend:1.0.0
    container_name: hrportalfrontend
    ports:
      - 3000:3000
    environment:
      - REACT_APP_DOMIAN=http://localhost:5000/


volumes:
  mongo_data: