version: '3'
services:
  mongodb:
    image: mongo
    container_name: mongo
    ports:
      - 27017:27017
    environment:
      - MONGO_INITDB_ROOT_USERNAME=klaus
      - MONGO_INITDB_ROOT_PASSWORD=klaus123
    volumes:
      - mongo_data:/data/db

  my-app:
    image: hr
    container_name: hr
    ports:
      - 5000:5000
    environment:
      - jwt_secret=secret
volumes:
  mongo_data: