const Applicants = [
    {
        name: "Sai Varshith",
        qualification: "B.Tech",
        department: "Software Developer",
        id: 1,
    },
    {
        name: "Sai Varshith",
        qualification: "B.Tech",
        department: "Software Developer",
        id: 1,
    },
    {
        name: "Sai Varshith",
        qualification: "B.Tech",
        department: "Software Developer",
        id: 1,
    },
    {
        name: "Sai Varshith",
        qualification: "B.Tech",
        department: "Software Developer",
        id: 1,
    },
    {
        name: "Sai Varshith",
        qualification: "B.Tech",
        department: "Software Developer",
        id: 1,
    },
    {
        name: "Sai Varshith",
        qualification: "B.Tech",
        department: "Software Developer",
        id: 1,
    },
    {
        name: "Sai Varshith",
        qualification: "B.Tech",
        department: "Software Developer",
        id: 1,
    },
    {
        name: "Sai Varshith",
        qualification: "B.Tech",
        department: "Software Developer",
        id: 1,
    },
    {
        name: "Sai Varshith",
        qualification: "B.Tech",
        department: "Software Developer",
        id: 1,
    },
    {
        name: "Sai Varshith",
        qualification: "B.Tech",
        department: "Software Developer",
        id: 1,
    },
    {
        name: "Sai Varshith",
        qualification: "B.Tech",
        department: "Software Developer",
        id: 1,
    },
    {
        name: "Sai Varshith",
        qualification: "B.Tech",
        department: "Software Developer",
        id: 1,
    },
    {
        name: "Sai Varshith",
        qualification: "B.Tech",
        department: "Software Developer",
        id: 1,
    },
    {
        name: "Sai Varshith",
        qualification: "B.Tech",
        department: "Software Developer",
        id: 1,
    },
    {
        name: "Sai Varshith",
        qualification: "B.Tech",
        department: "Software Developer",
        id: 1,
    },
    {
        name: "Sai Varshith",
        qualification: "B.Tech",
        department: "Software Developer",
        id: 1,
    },
    {
        name: "Sai Varshith",
        qualification: "B.Tech",
        department: "Software Developer",
        id: 1,
    },
    {
        name: "Sai Varshith",
        qualification: "B.Tech",
        department: "Software Developer",
        id: 1,
    },
    {
        name: "Sai Varshith",
        qualification: "B.Tech",
        department: "Software Developer",
        id: 1,
    },
    {
        name: "Sai Varshith",
        qualification: "B.Tech",
        department: "Software Developer",
        id: 1,
    },
    {
        name: "Sai Varshith",
        qualification: "B.Tech",
        department: "Software Developer",
        id: 1,
    },
    {
        name: "Sai Varshith",
        qualification: "B.Tech",
        department: "Software Developer",
        id: 1,
    },
    {
        name: "Sai Varshith",
        qualification: "B.Tech",
        department: "Software Developer",
        id: 1,
    },
    {
        name: "Sai Varshith",
        qualification: "B.Tech",
        department: "Software Developer",
        id: 1,
    },
    {
        name: "Sai Varshith",
        qualification: "B.Tech",
        department: "Software Developer",
        id: 1,
    },
    {
        name: "Sai Varshith",
        qualification: "B.Tech",
        department: "Software Developer",
        id: 1,
    },
    {
        name: "Sai Varshith",
        qualification: "B.Tech",
        department: "Software Developer",
        id: 1,
    },
    {
        name: "Sai Varshith",
        qualification: "B.Tech",
        department: "Software Developer",
        id: 1,
    },
    {
        name: "Sai Varshith",
        qualification: "B.Tech",
        department: "Software Developer",
        id: 1,
    },
    {
        name: "Sai Varshith",
        qualification: "B.Tech",
        department: "Software Developer",
        id: 1,
    },
    {
        name: "Sai Varshith",
        qualification: "B.Tech",
        department: "Software Developer",
        id: 1,
    },
    {
        name: "Sai Varshith",
        qualification: "B.Tech",
        department: "Software Developer",
        id: 1,
    },
    {
        name: "Sai Varshith",
        qualification: "B.Tech",
        department: "Software Developer",
        id: 1,
    },
    {
        name: "Sai Varshith",
        qualification: "B.Tech",
        department: "Software Developer",
        id: 1,
    },
    {
        name: "Sai Varshith",
        qualification: "B.Tech",
        department: "Software Developer",
        id: 1,
    },
    {
        name: "Sai Varshith",
        qualification: "B.Tech",
        department: "Software Developer",
        id: 1,
    },
    {
        name: "Sai Varshith",
        qualification: "B.Tech",
        department: "Software Developer",
        id: 1,
    },
    {
        name: "Sai Varshith",
        qualification: "B.Tech",
        department: "Software Developer",
        id: 1,
    },
    {
        name: "Sai Varshith",
        qualification: "B.Tech",
        department: "Software Developer",
        id: 1,
    },
    {
        name: "Sai Varshith",
        qualification: "B.Tech",
        department: "Software Developer",
        id: 1,
    },
    {
        name: "Sai Varshith",
        qualification: "B.Tech",
        department: "Software Developer",
        id: 1,
    },
    {
        name: "Sai Varshith",
        qualification: "B.Tech",
        department: "Software Developer",
        id: 1,
    },
    {
        name: "Sai Varshith",
        qualification: "B.Tech",
        department: "Software Developer",
        id: 1,
    },
    {
        name: "Sai Varshith",
        qualification: "B.Tech",
        department: "Software Developer",
        id: 1,
    },
    {
        name: "Sai Varshith",
        qualification: "B.Tech",
        department: "Software Developer",
        id: 1,
    },
    {
        name: "Sai Varshith",
        qualification: "B.Tech",
        department: "Software Developer",
        id: 1,
    },
    {
        name: "Sai Varshith",
        qualification: "B.Tech",
        department: "Software Developer",
        id: 1,
    },
    {
        name: "Sai Varshith",
        qualification: "B.Tech",
        department: "Software Developer",
        id: 1,
    },
    {
        name: "Sai Varshith",
        qualification: "B.Tech",
        department: "Software Developer",
        id: 1,
    },
    {
        name: "Sai Varshith",
        qualification: "B.Tech",
        department: "Software Developer",
        id: 1,
    },
    {
        name: "Sai Varshith",
        qualification: "B.Tech",
        department: "Software Developer",
        id: 1,
    },
    {
        name: "Sai Varshith",
        qualification: "B.Tech",
        department: "Software Developer",
        id: 1,
    },
    {
        name: "Sai Varshith",
        qualification: "B.Tech",
        department: "Software Developer",
        id: 1,
    },
    {
        name: "Sai Varshith",
        qualification: "B.Tech",
        department: "Software Developer",
        id: 1,
    },
    {
        name: "Sai Varshith",
        qualification: "B.Tech",
        department: "Software Developer",
        id: 1,
    },
    {
        name: "Sai Varshith",
        qualification: "B.Tech",
        department: "Software Developer",
        id: 1,
    },
    {
        name: "Sai Varshith",
        qualification: "B.Tech",
        department: "Software Developer",
        id: 1,
    },
    {
        name: "Sai Varshith",
        qualification: "B.Tech",
        department: "Software Developer",
        id: 1,
    },
    {
        name: "Sai Varshith",
        qualification: "B.Tech",
        department: "Software Developer",
        id: 1,
    },
    {
        name: "Sai Varshith",
        qualification: "B.Tech",
        department: "Software Developer",
        id: 1,
    },
    {
        name: "Sai Varshith",
        qualification: "B.Tech",
        department: "Software Developer",
        id: 1,
    },
    {
        name: "Sai Varshith",
        qualification: "B.Tech",
        department: "Software Developer",
        id: 1,
    },
    {
        name: "Sai Varshith",
        qualification: "B.Tech",
        department: "Software Developer",
        id: 1,
    },
    {
        name: "Sai Varshith",
        qualification: "B.Tech",
        department: "Software Developer",
        id: 1,
    },
    {
        name: "Sai Varshith",
        qualification: "B.Tech",
        department: "Software Developer",
        id: 1,
    },
    {
        name: "Sai Varshith",
        qualification: "B.Tech",
        department: "Software Developer",
        id: 1,
    },
    {
        name: "Sai Varshith",
        qualification: "B.Tech",
        department: "Software Developer",
        id: 1,
    },
    {
        name: "Sai Varshith",
        qualification: "B.Tech",
        department: "Software Developer",
        id: 1,
    },
    {
        name: "Sai Varshith",
        qualification: "B.Tech",
        department: "Software Developer",
        id: 1,
    },
    {
        name: "Sai Varshith",
        qualification: "B.Tech",
        department: "Software Developer",
        id: 1,
    },
    {
        name: "Sai Varshith",
        qualification: "B.Tech",
        department: "Software Developer",
        id: 1,
    },
    {
        name: "Sai Varshith",
        qualification: "B.Tech",
        department: "picskarnataka@gmail.com",
    },
];

module.exports = Applicants